### ISSUE TITLE
RPi._GPIO module not found

### ISSUE THREAD

**Issue by jacobscarter** [swkim01/RPi.GPIO-PineA64#2]
This error occurs when I attempt to import via

import RPi.GPIO as GPIO

**Comment by pklapperich** [comment]
Make sure to install RPi.GPIO. To install for the system python, do:
`sudo python setup.py install`

To install for python3 if python3 is not the system python, do 
`sudo python3 setup.py install`

**Comment by jieppu** [comment]
tried both, still not working 
?

**Comment by SecT0uch** [comment]
Solved. Can close this issue.

**Comment by jacobscarter** [comment]
What was the solution?

**Comment by SecT0uch** [comment]
I actually just get the same error.
It happend because I was in the same folder as the library. 
[Credits](https://forum.pine64.org/showthread.php?tid=723&pid=23682#pid23682)
