### ISSUE TITLE
fatal error: Python.h

### ISSUE THREAD

**Issue by valfa007** [swkim01/RPi.GPIO-PineA64#3]
when compile,there is an error:
building 'RPi._GPIO' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c source/py_gpio.c -o build/temp.linux-aarch64-2.7/source/py_gpio.o
source/py_gpio.c:23:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by swkim01** [comment]
You have to install python-dev package before compiling.

**Comment by SecT0uch** [comment]
Potentially solved and outdated. Can close this issue.
