### ISSUE TITLE
BOARD Mode, Pin Numbers higher than 26 give error

### ISSUE THREAD

**Issue by DonWh** [swkim01/RPi.GPIO-PineA64#4]
Using BOARD mode, when setting a pin mode (ex:   GPIO.setup(31, GPIO.OUT)    )pin numbers greater than 26 gives an error:  "ValueError: The channel sent is invalid on a Raspberry Pi".

Switching to BCM mode is a workaround.

Similar bug was noted in version 0.5.11 of RPi.GPIO for Pi.

**Comment by swkim01** [comment]
Sorry. I fixed the bug. Please reinstall by new source code.

**Comment by DonWh** [comment]
I confirmed that resolved the issue. Thanks.

**Comment by SecT0uch** [comment]
Solved. Can close this issue.
